### ISSUE TITLE
LORA moisture sensor v1.2 COMPILING ERROR and NRF ERROR

### ISSUE THREAD

**Issue by hakantapanyigit** [adafruit/RadioHead#69]
Hi, I'm working on Lora Moisture Sensor v1.2. I watched a tutorial ( [https://www.youtube.com/watch?v=4d9dZf8PyiU&t=429s](https://www.youtube.com/watch?v=4d9dZf8PyiU&t=429s) ) and ı did same things. But I have 3 problem; 

"""
1- C:\Users\hakan\Documents\Arduino\libraries\RadioHead-master\RH_NRF51.cpp: In member function 'void RH_NRF51::setModeRx()':

2- C:\Users\hakan\Documents\Arduino\libraries\RadioHead-master\RH_NRF51.cpp:158:21: error: assignment of read-only member 'NRF_CCM_Type::MICSTATUS' 
158 |  NRF_CCM->MICSTATUS = 0;

exit status 1

3- Compilation error for Adafruit Feather nRF52832 board.

"""

I could not find clue or answer anywhere. If someone can fixed this ı really pleasure. Thanks.

https://github.com/adafruit/RadioHead/blob/cfb46cf1ba591b1cf42dba5f33a99a70f6f46830/RH_NRF51.cpp#L158
